apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: skills-manager-postgres
  labels:
    app: skills-manager-postgres
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: skills-manager-postgres
  serviceName: skills-manager-postgres
  template:
    metadata:
      labels:
        app: skills-manager-postgres
    spec:
      containers:
        - name: postgres
          image: >-
            postgres:12.4-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: skills-manager-postgres-sec
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: skills-manager-postgres-sec
            - name: POSTGRES_DB
              value: skillsmanager_db
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              memory: 700Mi
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 200m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: skills-manager-postgres-pvc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: skills-manager-postgres-pvc
        labels:
          app: skills-manager-postgres
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: skills-manager-postgres-sc
